//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ptOS.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Event()
        {
            this.EventDatas = new HashSet<EventData>();
        }
    
        public long Id { get; set; }
        public Nullable<int> ServerId { get; set; }
        public Nullable<long> PlayerId { get; set; }
        public string Type { get; set; }
        public System.DateTime Submitted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventData> EventDatas { get; set; }
        public virtual Player Player { get; set; }
        public virtual Server Server { get; set; }
    }
}
