//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ptOS.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Player()
        {
            this.Events = new HashSet<Event>();
            this.Statistics = new HashSet<Statistic>();
        }
    
        public long Id { get; set; }
        public string Guid { get; set; }
        public string Username { get; set; }
        public string Ip { get; set; }
        public Nullable<int> LastServerId { get; set; }
        public Nullable<System.DateTime> FirstSeen { get; set; }
        public Nullable<System.DateTime> LastSeen { get; set; }
        public string LastCountry { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [Newtonsoft.Json.JsonIgnore]
        public virtual ICollection<Event> Events { get; set; }
        public virtual Server LastServer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [Newtonsoft.Json.JsonIgnore]
        public virtual ICollection<Statistic> Statistics { get; set; }
    }
}
